package com.theuran.mappet.api.events;

public enum EventType {
    ENTITY_DEATH,
    ENTITY_DAMAGE,

    SERVER_TICK,
    SERVER_STARTED,
    SERVER_STOPPED,
    SERVER_CHAT_MESSAGE,

    CLIENT_TICK,

    PLAYER_ATTACK_BLOCK,
    PLAYER_ATTACK_ENTITY,
    PLAYER_USE_BLOCK,
    PLAYER_USE_ENTITY,
    PLAYER_USE_ITEM,
    PLAYER_JOIN,
    PLAYER_DISCONNECT,
    PLAYER_PICKUP_ITEM,

    CLIENT_PLAYER_ATTACK_BLOCK,
    CLIENT_PLAYER_ATTACK_ENTITY,
    CLIENT_PLAYER_USE_BLOCK,
    CLIENT_PLAYER_USE_ENTITY,
    CLIENT_PLAYER_USE_ITEM
}
